"""r3

Revision ID: 0e958076d0b6
Revises: cce7b6d7834b
Create Date: 2024-06-01 17:21:41.462730

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = '0e958076d0b6'
down_revision = 'cce7b6d7834b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
