"""r

Revision ID: 52f08e7c795f
Revises: c4c851fe143b
Create Date: 2024-05-31 10:45:51.975021

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = '52f08e7c795f'
down_revision = 'c4c851fe143b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('favoriterecipe_recipe_id_fkey', 'favoriterecipe', type_='foreignkey')
    op.drop_constraint('favoriterecipe_user_id_fkey', 'favoriterecipe', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('favoriterecipe_user_id_fkey', 'favoriterecipe', 'user', ['user_id'], ['user_id'])
    op.create_foreign_key('favoriterecipe_recipe_id_fkey', 'favoriterecipe', 'recipe', ['recipe_id'], ['recipe_id'])
    # ### end Alembic commands ###
