"""Initial1

Revision ID: c4c851fe143b
Revises: e45e1cb372c0
Create Date: 2024-05-25 18:39:41.621385

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c4c851fe143b'
down_revision = 'e45e1cb372c0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'favoritefood', 'user', ['user_id'], ['user_id'])
    op.create_foreign_key(None, 'favoritefood', 'food', ['food_id'], ['food_id'])
    op.create_foreign_key(None, 'favoriterecipe', 'recipe', ['recipe_id'], ['recipe_id'])
    op.create_foreign_key(None, 'favoriterecipe', 'user', ['user_id'], ['user_id'])
    op.add_column('food', sa.Column('carbonhidrats', sa.Float(), nullable=False))
    op.drop_column('food', 'carbohydrates')
    op.add_column('recipe', sa.Column('carbonhidrats', sa.Float(), nullable=False))
    op.drop_column('recipe', 'carbohydrates')
    op.create_foreign_key(None, 'usermeal', 'meal', ['meal_id'], ['meal_id'])
    op.create_foreign_key(None, 'usermeal', 'food', ['food_id'], ['food_id'])
    op.create_foreign_key(None, 'usermeal', 'user', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usermeal', type_='foreignkey')
    op.drop_constraint(None, 'usermeal', type_='foreignkey')
    op.drop_constraint(None, 'usermeal', type_='foreignkey')
    op.add_column('recipe', sa.Column('carbohydrates', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('recipe', 'carbonhidrats')
    op.add_column('food', sa.Column('carbohydrates', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('food', 'carbonhidrats')
    op.drop_constraint(None, 'favoriterecipe', type_='foreignkey')
    op.drop_constraint(None, 'favoriterecipe', type_='foreignkey')
    op.drop_constraint(None, 'favoritefood', type_='foreignkey')
    op.drop_constraint(None, 'favoritefood', type_='foreignkey')
    # ### end Alembic commands ###
